import Header from '@/components/app/header/_header'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/components/app/nav/_nav'
import Title from '@/components/app/header/title/_title'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lukasz Baldyga',
  //description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="/favico.png" />
      <body className={inter.className}>
        <header>
          <Header>
            <Title text="Lukasz Baldyga"/>
            <Nav />
          </Header>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
