import Header from '@/components/app/header/_header'
import './globals.scss'
import style from "./layout.module.scss";
import type { Metadata } from 'next'
import Nav from '@/components/app/nav/_nav'
import Title from '@/components/app/header/title/_title'
import Footer from '@/components/app/footer/_footer'
import { Tooltip } from 'react-tooltip';

export const metadata: Metadata = {
  title: 'Lukasz Baldyga',
  //description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="/favico.png" />
      <body className={style.body}>
        <header>
          <Header>
            <Title text="Lukasz Baldyga"/>
            <Nav />
          </Header>
        </header>
        <main>
          {children}
        </main>
        <Footer/>
        {/* Extra stuff */}
        <Tooltip id={"default"}/>
      </body>
    </html>
  )
}
