name: Test Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo docker buildx build .
